### ISSUE TITLE
compiler warning on Xcode 6.3

### ISSUE THREAD

**Issue by jurvis** [shu223/PulsingHalo#18]
PulsingHaloLayer returns a compiler error:
`Auto property synthesis will not synthesize property 'repeatCount'; it will be implemented by its superclass, use @dynamic to acknowledge intention`

sent pull request [#17](https://github.com/shu223/PulsingHalo/pull/17) with fix by adding `@dynamic repeatCount` to implementation

**Comment by shu223** [comment]
I've merged, thanks!
