### ISSUE TITLE
Multiple pulsing layer class not in cocoapod 

### ISSUE THREAD

**Issue by samjarman** [shu223/PulsingHalo#21]
Line 10 here: https://github.com/shu223/PulsingHalo/blob/master/PulsingHalo.podspec needs adjusting :)

**Comment by hadimichael** [comment]
Line 10 is fine. It looks like the central CocoaPods spec is a little old and needs to be updated (https://github.com/CocoaPods/Specs/blob/master/Specs/PulsingHalo/0.0.1/PulsingHalo.podspec.json).

@shu223: Please see this guide for updating: https://guides.cocoapods.org/making/specs-and-specs-repo.html#how-do-i-update-an-existing-pod

In the mean time, we can use this in our Podfile: 
```pod 'PulsingHalo', :git => 'https://github.com/shu223/PulsingHalo.git', :tag => '0.0.5'```

**Comment by simonbromberg** [comment]
Does the MultiplePulsingHalo work for you? It just comes up as a solid, non animating circle for me

**Comment by samjarman** [comment]
@simonbromberg nah it didnt work for me

**Comment by hadimichael** [comment]
@simonbromberg @samjarman it works for me. I definitely had a similar issue (non animating circle), but I can't quite remember what it was that fixed it. Have a good look at the example and make sure that's working for you.

**Comment by revolter** [comment]
@shu223 Doesn't this mean that the [color section](https://github.com/shu223/PulsingHalo#color) from the documentation in the `README` is incorrect?

**Comment by shu223** [comment]
Please try the new release [0.0.6](https://github.com/shu223/PulsingHalo/releases/tag/0.0.6).
