### ISSUE TITLE
MultiHalo not working

### ISSUE THREAD

**Issue by B-Rass** [shu223/PulsingHalo#24]
Hi ! 

First thanks for this great code.

I just have problem with integrating multiple Halo, but I have none with the simple one. 
And of course, I need the multiple one ^^

I instantiate it in my specific view, as the documentation and the demo showed me. 

Cheers !

**Comment by unseenmachines** [comment]
Same here, using iOS 8.4. PulsingHaloLayer works fine. I noticed that buildSublayers prints out "sub count:0"

**Comment by AndrewSB** [comment]
Same here

**Comment by legendstar177** [comment]
same here, i realized that when I put window or navigation.view addSublayer multiHalo just show a single one, but when i add it through view, it worked fine. But what I want is adding it into window :( . Help me

**Comment by andrey-lisovskiy** [comment]
Same problem, MultiHalo isn't working

**Comment by shu223** [comment]
Please try the new release [0.0.6](https://github.com/shu223/PulsingHalo/releases/tag/0.0.6).
