### ISSUE TITLE
How to use on swift?

### ISSUE THREAD

**Issue by nassarofficial** [shu223/PulsingHalo#28]
How could I initiate a pulse on swift?

**Comment by acegreen** [comment]
var activityIndicator: PulsingHaloLayer!

                self.activityIndicator = PulsingHaloLayer(layerNumber: 3)
                self.activityIndicator.position = getCenterOfView(self.view)
                self.activityIndicator.radius = self.view.bounds.height / 2
                self.activityIndicator.backgroundColor = UIColor.grayColor().CGColor
                self.activityIndicator.useTimingFunction = false
                self.view.layer.addSublayer(self.activityIndicator)

**Comment by shu223** [comment]
Hi, I updated the README.
