### ISSUE TITLE
Fix the non modular error

### ISSUE THREAD

**Issue by harryworld** [shu223/PulsingHalo#34]
This appears in my project

```
Include of non-modular header inside framework module 'PulsingHalo.PulsingHalo'
```

https://github.com/jessesquires/JSQMessagesViewController/pull/1284

**Comment by harryworld** [comment]
I am sending pull request here https://github.com/shu223/PulsingHalo/pull/35

**Comment by shu223** [comment]
Thanks for your pull request! It has been merged!
