### ISSUE TITLE
Stop animation

### ISSUE THREAD

**Issue by brightsider** [shu223/PulsingHalo#36]
How to stop animation and start again after some interval?

**Comment by mouse-lin** [comment]
I think stop func is not exist.
I remove PulsingHaloLayer when want it to stop and add it to super layer when want it to start

**Comment by shu223** [comment]
Please use [Pulsator](https://github.com/shu223/Pulsator) which is the new version of this PulsingHalo written with Swift. It has stop method.

**Comment by mouse-lin** [comment]
@shu223 ok, thx
