### ISSUE TITLE
App back to the foreground stop pulsing

### ISSUE THREAD

**Issue by kshysius** [shu223/PulsingHalo#37]
Hi, 

I try press home button ant then i back to app PulsingHalo stop pulsing

i try add this in PulsingHaloLayer.m:

```
  (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)flag {
 		  
    if (flag) {
       [self removeAllAnimations];
       [self removeFromSuperlayer];
    }
  }
```

but not working

**Comment by baallalAbderrahim** [comment]
i'm having the same issue , could you help please ?
thanks

**Comment by genaks** [comment]
same here

**Comment by shu223** [comment]
I created updated version named "Pulsator" which is written in Swift.

https://github.com/shu223/Pulsator

This problem has been fixed at the repo. Usage is almost same.
