### ISSUE TITLE
Problem with podspec file

### ISSUE THREAD

**Issue by sandman4sure** [shu223/PulsingHalo#41]
See issue https://github.com/CocoaPods/CocoaPods/issues/4636
The deployment target will be set to 4.3 if no target is added to the podspec file.
This will result in a compile error.

**Comment by shu223** [comment]
@sandman4sure thanks, i didn't know that problem. I just updated the podspec, could you try this?

**Comment by sandman4sure** [comment]
When downloading the source for 0.25, the updated podspec file is not included.

**Comment by sandman4sure** [comment]
@shu223 can you make a new branch with the podfile changes added? Latest branch you made didn't include your last change.

**Comment by revolter** [comment]
I know this is maintained anymore but it would be awesome if it would be left in a working state.

**Comment by shu223** [comment]
Fixed now, I'm so sorry for my late support.
