### ISSUE TITLE
PulsingHaloLayer.m:28:1: Cannot synthesize weak property because the current deployment target does not support weak references

### ISSUE THREAD

**Issue by gregk8288** [shu223/PulsingHalo#42]
I receive the following error when trying to compile a debug version of the app. 

`/Users/gregkockott/www/Mobile-App-iOS/Pods/PulsingHalo/PulsingHalo/PulsingHaloLayer.m:28:1: Cannot synthesize weak property because the current deployment target does not support weak references`

``
@implementation PulsingHaloLayer <-- HERE IS THE ISSUE
``

**Comment by TianDaGe** [comment]
@property (nonatomic, weak) CALayer *prevSuperlayer;
I fixed as like this
@property (nonatomic, strong) CALayer *prevSuperlayer;

**Comment by CavalcanteLeo** [comment]
@TianDaGe submit a pull request, that fixed...

**Comment by faimin** [comment]
stackoverflow had a solution: [http://stackoverflow.com/questions/37160688/set-deployment-target-for-cocoapodss-pod](http://stackoverflow.com/questions/37160688/set-deployment-target-for-cocoapodss-pod)

```cocoaPods
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'PulsingHalo'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.2'
            end
        end
    end
end
```

**Comment by lappp9** [comment]
@TianDaGe If you make that property strong you'll at least have a retain cycle until you remove the halo view from its superView

**Comment by shu223** [comment]
Fixed now, I'm so sorry for my late support.

https://github.com/shu223/PulsingHalo/commit/255eacebdf7b4ba2314429649ae076aa104a07cb

The `ios.deployment_target` didn't work with the wrong order in the podspec.

Please try the  0.2.8 and let me know if there is still problems.
