### ISSUE TITLE
My app got rejected due to use of non-public APIs

### ISSUE THREAD

**Issue by nikhilolx** [shu223/PulsingHalo#45]
Hi

My app got rejected with following reason:
Your app uses or references the following non-public APIs:
- ‘GraphicsServices.framework’

Kindly help.

**Comment by shu223** [comment]
@nikhilolx I don't think this library uses "GraphicsServices.framework". I have used this library in some apps and have never be rejected for this library. Could you let me know the whole sentence from Apple (without any private/confidential info)?
