### ISSUE TITLE
Setting Duration and Radius

### ISSUE THREAD

**Issue by thetripler** [shu223/PulsingHalo#7]
Hello,

I seem to be having trouble with the callbacks to the PulsingHaloClass

The INIT values load correctly, but after the ViewDidLoad runs there are no connections being made back to the "PulsingHaloLayer"

None of these connections are working to adjust the halo:

[self setupInitialValues];
- (IBAction)radiusChanged:
- (IBAction)colorChanged:

My Method:
- (void)HaloProximityFar {
    
    self.halo.radius = 140;
    self.halo.animationDuration = 12; 
}

I'm using iOS7.1 with ARC and Storyboards and added using CocoaPods

Thanks

Michael

**Comment by shu223** [comment]
Please try the new release [0.0.6](https://github.com/shu223/PulsingHalo/releases/tag/0.0.6). It supports dynamic changing for `animationDuration`.
